"""Write the four src/*.liquid layouts from one body and four knob blocks.

The layouts are one template that differs only in its knobs, and hand
editing four copies is how they drift. `scripts/check.sh` regenerates and
fails if the working tree disagrees, so the body below is the only place
the render is written.
"""
import pathlib, sys

BODY = pathlib.Path(__file__).with_name('layout_body.liquid').read_text()

SHARED = """{%- assign src = google_calendar_12345 -%}

{%- comment -%} ---- colours: overridden by the plugin's custom fields ---- {%- endcomment -%}
{%- assign CAL_MAP_DEFAULT = "you@gmail.com=black,work@example.com=red,shared@group.calendar.google.com=yellow" -%}
{%- assign DEFAULT_COLOR_FALLBACK = "black" -%}
{%- assign LIGHT_FILLS = "white,yellow,gray-10,gray-15,gray-20,gray-25,gray-30,gray-35" | split: "," -%}

{%- comment -%} ---- layout ---- {%- endcomment -%}
{%- assign SHOW_ALLDAY = true -%}
{%- assign HIGHLIGHT_TODAY = true -%}
{%- assign DAY_FMT = "%a %-m/%-d" -%}
{%- assign HEAD_SIZE = "small" -%}   {%- comment -%} label--small is the framework's 12px pixel-hinted
                                          face (TRMNL12). label--xsmall is an ALIAS of the 16px one, so
                                          it is not smaller; nothing below 12px renders without fuzz. {%- endcomment -%}
{%- assign AXIS_MODE_FALLBACK = "fit" -%}
{%- assign EMPTY_START_H = 8 -%}
{%- assign EMPTY_END_H = 18 -%}
{%- assign LINE_H = 12 -%}
{%- assign CHAR_W100 = 665 -%}   {%- comment -%} hundredths of a px per character of the 12px face, measured live {%- endcomment -%}
{%- assign MAX_DEPTH = 4 -%}     {%- comment -%} nesting steps a block is indented for; deeper ones share the last step {%- endcomment -%}
{%- assign MIN_AXIS_DUR = 5 -%}   {%- comment -%} minutes: shorter than this and the event does not move the axis {%- endcomment -%}
"""

LAYOUTS = {
    # view              days panelW axis panelH head (unused) hmax every one_line title legend indent
    'full':            (3, 780, 39, 460, 18, 44, 24, 1, 36, 35, 'true', 24),
    'half_horizontal': (3, 780, 39, 220, 18, 36, 16, 3, 36, 35, 'true', 24),
    'half_vertical':   (2, 380, 40, 460, 18, 44, 22, 2, 24, 23, 'false', 16),
    'quadrant':        (2, 380, 34, 220, 18, 36, 15, 3, 25, 24, 'false', 16),
}

HEAD = """{%- comment -%}
=====================================================================
 Google Calendar fork - per-calendar colour coding (TRMNL Plugin Merge)
 Layout: @VIEW@
 View:   3 Day Week time grid. Hours down the left axis, one column per
         day. Every event is a solid filled block carrying its start
         time, end time and title in full. Blocks sit at their clock
         position; a block that starts inside another is indented and
         painted over it, as the native render does, but never over
         the other block's text.
=====================================================================
 GENERATED by scripts/gen_layouts.py from scripts/layout_body.liquid.
 Edit those, run the script, never these files.
=====================================================================
 SETUP
   1. Connect Google Calendar natively, pick your calendars, hide the
      instance on the playlist so it keeps syncing.
   2. New Private Plugin -> Strategy: Plugin Merge.
   3. Open "Merge Variables", find your node (google_calendar_<id>) and
      replace the placeholder on the `assign src` line below.
   4. Set the colours on the plugin's settings page, not here: the
      "Calendar colors" field takes one `calendar-id=colour` per line and
      "Default color" covers anything unlisted. The defaults below apply
      only while those fields are empty.

 COLOURS. On the TRMNL OG (B/W/R/Y) panel only black, white, red and
 yellow are solid inks; every other token is dithered into a speckle and
 reads as fuzz. Grey steps are for 1-bit and TRMNL X panels only.
=====================================================================
{%- endcomment -%}

"""

KNOBS = """{%- comment -%} ---- this layout ---- {%- endcomment -%}
{%- assign VIEW = "@VIEW@" -%}
{%- assign NUM_DAYS = @DAYS@ -%}          {%- comment -%} day columns, starting today {%- endcomment -%}
{%- assign PANEL_W = @PANEL@ -%}         {%- comment -%} USABLE width: the panel less the framework .screen's 10px
                                            box inset on each side. The columns divide it into whole px {%- endcomment -%}
{%- assign AXIS_W = @AXIS@ -%}           {%- comment -%} chosen so (PANEL_W - AXIS_W) / NUM_DAYS is exact {%- endcomment -%}
{%- assign PANEL_H = @PANELH@ -%}        {%- comment -%} USABLE height, same inset. The grid gets what the day
                                            headers, the all-day band and the legend leave of it {%- endcomment -%}
{%- assign HEAD_H = @HEADH@ -%}          {%- comment -%} day-header row, measured in the rendered preview {%- endcomment -%}
{%- assign HOUR_H_MAX = @HMAX@ -%}         {%- comment -%} px per hour ceiling {%- endcomment -%}
{%- assign HOUR_EVERY = @EVERY@ -%}         {%- comment -%} label every Nth hour {%- endcomment -%}
{%- assign ONE_LINE_CHARS = @ONELINE@ -%}   {%- comment -%} "start - end  Title" that fits the column on one line {%- endcomment -%}
{%- assign TITLE_CHARS = @TITLE@ -%}       {%- comment -%} a title longer than this is the only thing ever truncated {%- endcomment -%}
{%- assign INDENT_W = @INDENT@ -%}         {%- comment -%} px a nested block steps right per open block above it {%- endcomment -%}
{%- assign SHOW_LEGEND = @LEGEND@ -%}

"""

def render(view):
    (days, panel, axis, panel_h, head_h, title_h, hmax, every,
     one_line, title, legend, indent) = LAYOUTS[view]
    subs = {'@VIEW@': view, '@DAYS@': days, '@PANEL@': panel, '@AXIS@': axis,
            '@PANELH@': panel_h, '@HEADH@': head_h,
            '@HMAX@': hmax, '@EVERY@': every,
            '@ONELINE@': one_line, '@TITLE@': title, '@LEGEND@': legend,
            '@INDENT@': indent}
    out = HEAD + SHARED + '\n' + KNOBS + BODY
    for k, v in subs.items():
        out = out.replace(k, str(v))
    return out

if __name__ == '__main__':
    check = '--check' in sys.argv
    root = pathlib.Path(__file__).resolve().parent.parent
    bad = []
    for view in LAYOUTS:
        p = root / 'src' / f'{view}.liquid'
        out = render(view)
        if check:
            if not p.exists() or p.read_text() != out:
                bad.append(str(p))
        else:
            p.write_text(out)
    if check and bad:
        print('FAIL: regenerate the layouts - ' + ', '.join(bad))
        sys.exit(1)
    print('layouts checked' if check else 'layouts written')
